### PR TITLE
Update What Makes Ravencoin Different from Bitcoin?

### PR DESCRIPTION
**Pull request by dicklarsson**
Removed line "Block reward of 5,000 RVN instead of 50 BTC" from front page.

### CODE REVIEW

**Comment by Tylerlhess** [comment]
I think it just needs "Initial" on the front for. 
"Initial block reward of 5,000 RVN instead of 50 BTC"

**Comment by dicklarsson** [comment]
We need a web site that that describes Ravencoin in a concise and clear way. 
Having outdated information is TOTALLY confusing. 
No information is better than confusing information ;)

**Review by jeroz1 — APPROVED** [review]

**Comment by jeroz1** [comment]
This is also addressed in #238.

**Comment by jeroz1** [comment]
Closing, since it was previously addressed. Feel free make a new PR if you think it's not clear enough and have a better suggestion.

**Comment by jeroz1** [comment]
reopening to make the block reward info on the index page reflect the info on the about page.

**Review by jeroz1 — CHANGES_REQUESTED** [review]
please update to reflect the info on the about page.

**Pull request closed without merging**
