### PR TITLE
Update projects.yml

### PR DESCRIPTION
**Pull request by MilkshakeMan69**
Rikki RVNFT kindly asked me to add this

### CODE REVIEW

**Comment by RVNFT** [comment]
Thanks for adding this for me :)

**Comment by jeroz1** [comment]
Could you update this to match with the current projects page?

**Review by jeroz1 — APPROVED** [review]

**Comment by jeroz1** [comment]
fixed it for you :)

**Comment by RVNFT** [comment]
Thank you! Sorry, it's an American holiday today so I'm out and about, away from the computer 😁

Sent from ProtonMail mobile

-------- Original Message --------

**Pull request merged**
