### PR TITLE
Update community.md

### PR DESCRIPTION
**Pull request by Kaiget**
Replaced dead discord link with a link to The Birdhouse community.

### CODE REVIEW

**Comment by Kaiget** [comment]
Let me know if you need anything else from me.

**Review by SpicyRVN — COMMENTED** [review]
No lol.

**Comment by Kaiget** [comment]
Why's that? Makes sense to replace a dead link with an active working community.

**Review by Tylerlhess — CHANGES_REQUESTED** [review]
This discord link isn't dead.

**Comment by Kaiget** [comment]
It was when I submitted this 6 months ago. Now it appears to go to a server that requires a wallet verification to enter, seems scummy. Which is worse than dead.

**Comment by Tylerlhess** [comment]
Ah I just was checking the changes not the site itself. There are 3 discords listed here I think this would go over better by adding The Birdhouse Community as a fourth discord. I am not sure what that community is about, I am not a part of it.

**Comment by SpicyRVN** [comment]
I think we should add this server instead of the birdhouse server because it serves a much more direct and useful purpose for Raven. https://discord.com/invite/Y86KU3Bz

**Comment by Tylerlhess** [comment]
> I think we should add this server instead of the birdhouse server because it serves a much more direct and useful purpose for Raven. https://discord.com/invite/Y86KU3Bz

I am opposed to this for the simple fact that I don't want to have to moderate that discord and was hoping to keep it an open secret.

**Comment by Kaiget** [comment]
Closing.

**Pull request closed without merging**
