### PR TITLE
Add Logo Digitalexchange.id

### PR DESCRIPTION
**Pull request by WMSena**

### CODE REVIEW

**Review by jeroz1 — COMMENTED** [review]
Thank you for your pull request.

Could you adjust your change such that all exchanges are in alphabetical order?

**Comment by WMSena** [comment]
> Thank you for your pull request.
> 
> Could you adjust your change such that all exchanges are in alphabetical order?

thanks for letting me know, I've changed the exchanges to alphabetical order.

**Comment by WMSena** [comment]
> Thank you for your pull request.
> 
> Could you adjust your change such that all exchanges are in alphabetical order?

Hello, I've changed the file name to digitalexchange.png and use the right ratio for the file.

**Comment by jeroz1** [comment]
The image that you added had the size 450x73 pixels.

I changed it to 450x150 to correct the ratio. 

Please review and change it in the pull request.  

digitalexchange

**Review by jeroz1 — APPROVED** [review]
Tested ACK

**Pull request merged**
