### PR TITLE
Update community.md

### PR DESCRIPTION
**Pull request by ShortsellerEnrichmentCommission**
Updated discord link

### CODE REVIEW

**Comment by JohnELester** [comment]
What do you mean exactly by "updated?"  The current link to Discord works perfectly (https://discord.gg/jn6uhur) and points to the main Discord server.   The link you are proposing is invalid and expired.

**Comment by ShortsellerEnrichmentCommission** [comment]
> What do you mean exactly by "updated?"
> 
> The current link to Discord works perfectly (https://discord.gg/jn6uhur) and points to the main Discord server.
> 
> The link you are proposing (https://discord.gg/sntqk8) is invalid and expired.

I have updated the link, it is no longer invalid or expired.

**Comment by JohnELester** [comment]
I see your updates.  

Now you are proposing to **delete** the link to the current main Discord (https://discord.gg/jn6uhur) and **replace** it with a link to the completely new Discord (https://discord.gg/H7KaQ2j) that you set up when you were banned from the main Discord.  

That's not cool at all.

**Comment by ShortsellerEnrichmentCommission** [comment]
> I see your updates.
> 
> Now you are proposing to **delete** the link to the current main Discord (https://discord.gg/jn6uhur) and **replace** it with a link to the completely new Discord (https://discord.gg/H7KaQ2j) that you set up when you were banned from the main Discord.
> 
> That's not cool at all.

But it is cool to only have the main one?

**Comment by blondfrogs** [comment]
Can we just close this PR please @JohnELester. Can you give we read/write access to this repo and I can close it?

**Comment by ShortsellerEnrichmentCommission** [comment]
> Can we just close this PR please @JohnELester. Can you give we read/write access to this repo and I can close it?

Really?

**Comment by blondfrogs** [comment]
You could of created a pull request that adds the new discord info in addition to the old discord. That would of been fine, but you can't just create something the replaces an existing usable system because you were banned. That doesn't seem very fair at all.

**Comment by ShortsellerEnrichmentCommission** [comment]
> You could of created a pull request that adds the new discord info in addition to the old discord. That would of been fine, but you can't just create something the replaces an existing usable system because you were banned. That doesn't seem very fair at all.

There is one now. See pull 18. I expect that you will ask with as much intent to have it merged.

**Comment by blondfrogs** [comment]
I know there is, that is why I am closing this PR.

**Comment by ShortsellerEnrichmentCommission** [comment]
> I know there is, that is why I am closing this PR.

When do I get my write access? Or I don't because I'm a part of the hoi polloi?

**Pull request closed without merging**
