### PR TITLE
Updated the mootree project link

### PR DESCRIPTION
**Pull request by PhilRicher**
This PR is quite simple: I simply corrected a typo and modified the link to the Moontree project which ended up on a 404 page.

### CODE REVIEW

**Review by jeroz1 — CHANGES_REQUESTED** [review]
I don’t see the the benefit of adding the gem webrick here. 

It’s also not part of the problem being solved.

**Comment by PhilRicher** [comment]
To be honest I have no experience with this language. I just wanted to do an update on the Moontree project link but I had to use the webrick gem locally to be able to run the site. So can we just remove the modification from the webrick gem?

**Comment by jeroz1** [comment]
Thanks, and yep :)

**Review by jeroz1 — APPROVED** [review]

**Comment by PhilRicher** [comment]
Done.  Could I ask how the website actually works with GitHut? I develop websites with different technologies but this is my first time using Jekyll/Liquid. Very special as a language. Do you have any links to instruct me or a high level explanation so I understand how GitHub hosts our website?  Also are you the one and only "master" of the website project who has control over the PR?  Thanks!

**Comment by jeroz1** [comment]
More info here: 

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll

https://jekyllrb.com/docs/github-pages/

I’m not the only one with control over PRs. You’ll find a list under reviewers when making a pull request. 

I was just fast to respond.

**Comment by PhilRicher** [comment]
Thank you.

**Pull request merged**
