### PR TITLE
Updating Exchanges

### PR DESCRIPTION
**Pull request by soullesscomputerboy**
Removed Altilly - Hacked and no longer operating
Removed Barterdex - No longer lists RVN
Removed Coinall - seems to be no longer operating
Fixed dextrade link - removed BTC/RVN pair
Removed Diger - no longer exists
Removed Exolix - removed RVN from exchange
Removed Gazua - no longer operating
Removed QBTC - website is offline
Fixed TZero - link was 404, changed link to homepage
Removed Vertbase - No longer operating

Fixed order of exchanges to alphabetical
Removed old images that are no longer being used

### CODE REVIEW

**Comment by soullesscomputerboy** [comment]
I believe I should have formatted this pull request very differently. Sorry for the jumbled mess. If there is something I can do to tidy up the pull request let me know. I am very new to github and just trying to help out.

**Comment by soullesscomputerboy** [comment]
Please don't merge this until I clean the PR up. Thanks.

**Comment by soullesscomputerboy** [comment]
I *think* I have cleaned this up now. If there is anything else that needs to be done in this PR let me know.

**Review by fdoving — APPROVED** [review]
Looks good to me.

**Comment by jeroz1** [comment]
Thanks for this!

Vertbase actually rebranded to Sequoir.

https://app.sequoir.com/assets/rvn

afaik they also donate trading fees to the project.

Would it be possible to add it? I could make the png logo if needed.

**Comment by soullesscomputerboy** [comment]
> 
> 
> Thanks for this!
> 
> Vertbase actually rebranded to Sequoir.
> 
> https://app.sequoir.com/assets/rvn
> 
> afaik they also donate trading fees to the project.
> 
> Would it be possible to add it? I could make the png logo if needed.

If you make the logo I can add it in super easily. I checked for press/branding on their website but it just asks to email them. If you want me to go that route to get the logo I could do that instead.

**Pull request closed without merging**
