### PR TITLE
Insert Revain widget

### PR DESCRIPTION
**Pull request by flashcraft**
Reviews widget from Revain.

### CODE REVIEW

**Review by TronBlack — APPROVED** [review]

**Review by jeroz1 — APPROVED** [review]

**Comment by jeroz1** [comment]
Looks cool.

**Comment by TronBlack** [comment]
`Uncaught TypeError: Cannot read property 'getItem' of null
    at i (storage.js:26)
    at Object.set (storage.js:30)
    at Object.<anonymous> (history.js:14)
    at f (review-carousel?companyType=Project&companySlug=ravencoin&consumer=https%3A%2F%2Fravencoin.org&contentLines=4&elevationLevel=2&writeReviewAt=6&sortBy=recent&perPage=9&bg=neutral.0&reviewLocale=en&ratingProgressFill=%23eb9c35&blockchainLinkColor=%231f89e5&showMoreLinkColor=%231f89e5&dataSource=null&locale=en&theme=default:45)
    at Object.<anonymous> (historyActions.js:3)
    at f (review-carousel?companyType=Project&companySlug=ravencoin&consumer=https%3A%2F%2Fravencoin.org&contentLines=4&elevationLevel=2&writeReviewAt=6&sortBy=recent&perPage=9&bg=neutral.0&reviewLocale=en&ratingProgressFill=%23eb9c35&blockchainLinkColor=%231f89e5&showMoreLinkColor=%231f89e5&dataSource=null&locale=en&theme=default:45)
    at Object.<anonymous> (widget.v2.823c0fd6.chunk.js:2)
    at f (review-carousel?companyType=Project&companySlug=ravencoin&consumer=https%3A%2F%2Fravencoin.org&contentLines=4&elevationLevel=2&writeReviewAt=6&sortBy=recent&perPage=9&bg=neutral.0&reviewLocale=en&ratingProgressFill=%23eb9c35&blockchainLinkColor=%231f89e5&showMoreLinkColor=%231f89e5&dataSource=null&locale=en&theme=default:45)
    at Object.<anonymous> (widget.v2.823c0fd6.chunk.js:2)
    at f (review-carousel?companyType=Project&companySlug=ravencoin&consumer=https%3A%2F%2Fravencoin.org&contentLines=4&elevationLevel=2&writeReviewAt=6&sortBy=recent&perPage=9&bg=neutral.0&reviewLocale=en&ratingProgressFill=%23eb9c35&blockchainLinkColor=%231f89e5&showMoreLinkColor=%231f89e5&dataSource=null&locale=en&theme=default:45)
The resource https://revain.org/static/media/rv-icons.c70efeb0.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
DevTools failed to load SourceMap: Could not parse content for https://revain.org/widget-v2/runtime-widget.v2.c9f2a8ec.js.map: Unexpected token < in JSON at position 0`

**Comment by jeroz1** [comment]
Where/when did you encounter this error @TronBlack ?

When I built this code locally, I did not encounter this error.

**Comment by TronBlack** [comment]
In Brave browser, viewing the Javascript Console, when the reviews didn't show up.
It works in Safari.

If I drop the shields in Brave, I get the reviews, with some other warnings:

A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Pull request merged**
