### PR TITLE
Adding Edge wallet to 3rd Party Wallets

### PR DESCRIPTION
**Pull request by chadyo**
Forked site: https://chadyo.github.io

Edge now supports Ravencoin. Please consider adding it to list of 3rd party wallets.

### CODE REVIEW

**Comment by chadyo** [comment]
@blondfrogs thanks for merging! I see there's also a ravencoin.com site with a different repo but looks like the same codebase. Does this change to the .org repo get moved over to the .com site eventually somehow or should I make the same change to that repo? Thanks

**Comment by jeroz1** [comment]
It will be moved over.

**Comment by chadyo** [comment]
@jeroz1 just checking back in, I still don't see this change over on the .com site. Any idea when it will be moved over? thanks!

**Comment by jeroz1** [comment]
@chadyo this git is directly linked to the .org site. 

@blondfrogs needs to pull a switch to manually forward the update to the .com site. I bet he forgot :)

**Comment by chadyo** [comment]
@blondfrogs are you able to forward this update to the .com site? See above thread, thanks

**Pull request merged**
