### PR TITLE
Add Jackdaw to Projects page

### PR DESCRIPTION
**Pull request by Kaiget**
Let me know of this didn't work right github was giving me a hard time on mobile. Just looking to get the Jackdaw project and it's applicable links added to the "Projects" section of Ravencoin.org.

### CODE REVIEW

**Comment by Kaiget** [comment]
I set the community.md page back to how it was for this PR, I closed the previous PR with that change added.

**Review by Kaiget — COMMENTED** [review]
Caught a type-o

**Review by jeroz1 — CHANGES_REQUESTED** [review]
Whitepaper link is dead

**Comment by Kaiget** [comment]
Ah yeah I'll get that changed and resubmit

**Comment by Kaiget** [comment]
Fixed. You should be able to access the qhitepaper via the link provided now, sorry about that I changed the slug and didn't realize I had it linked here. Great catch, thank you Jeroz.

**Review by jeroz1 — CHANGES_REQUESTED** [review]
The special character @ has meaning in YAML. If you want to use it in your text, you need to add quotes.  

Please update line 264 in ./_data/projects.yml to:

`- name: "@JackdawCrypto on X"`

See: https://yaml.org/spec/1.2.2/#53-indicator-characters

**Review by jeroz1 — APPROVED** [review]
Tested ACK

**Pull request merged**
