### PR TITLE
added discord 2, reddit 2, getravencoin.org.

### PR DESCRIPTION
**Pull request by russkidooski**

### CODE REVIEW

**Comment by MS1LVA** [comment]
The community is growing and I believe its appropriate to share all community channels if they provide some value to the users. I own a operate GetRavencoin.org and have asked @russkidooski to include that in his PR.

**Comment by russkidooski** [comment]
the community should have a choice to join whatever reddit/discord they want. i am not closing this PR

**Comment by mcshinskyredlist** [comment]
This is already merged but I would have to disagree as well. Too many chiefs and too many sites of "centralized" can create misleading information when the sites conflict each other. I would find it more productive to the community to merge the best assets of sites like getravencoin.org into ravencoin.com and grow the contributor pool here.

**Comment by mmcshinsky** [comment]
This is already merged but I would have to disagree as well. Too many chiefs and too many sites "centralizing data individually" can create misleading information when the sites conflict each other. I would find it more productive to the community to merge the best assets of sites like getravencoin.org into ravencoin.com and grow the contributor pool here.

This works best here especially since ravencoin is open source for correcting information on the site.

**Comment by MS1LVA** [comment]
@mmcshinsky I agree Ravencoin.com should contain the best information and content on the web for Ravencoin. I am more than willing to contribute the only different feature between sites, a latest news and media from the community section, if that's what I could provide to benefit Ravencoin.com. The website aside, GetRavencoin.org is also a entity that is interested in the promotion of Ravencoin through organic channels. In regards to the websites, Ravencoin does benefit from the larger digital footprint provided by them. Essentially by giving Ravencoin.com and .org more domain authority.

**Comment by mmcshinsky** [comment]
@MS1LVA I have to apologize. You bring up a great point on domain authority, cross linking and such to bring up the SEO value of the community and visibility to the project resources. These were points I had failed to consider thoroughly previously.

**Pull request merged**
