### PR TITLE
[WIP] Adding ledger tutorial and BXB exchange.

### PR DESCRIPTION
**Pull request by jeroz1**
- Added Ledger Tutorial on page /ledger/ (Issue #53) 
- Added exchange BXB to exchange list (Issue #73)

### CODE REVIEW

**Comment by jeroz1** [comment]
Do not merge yet. The tutorial contains some errors still. I am talking with @traysi about it.

**Comment by RealBokito** [comment]
Any update on this PR? Would it be possible to merge the BXB logo (one of the sponsor of the Korean meetup) separately?

**Comment by jeroz1** [comment]
I moved it to pull #75. That one has several August exchanges

**Comment by blondfrogs** [comment]
@jeroz1 Because we merged the august PR, this PR now has conflicts. Can you update it so the conflicts are resolved.

**Comment by jeroz1** [comment]
@blondfrogs yes I will as soon as there is more clarity on the ledger integration progress.

**Comment by blondfrogs** [comment]
@jeroz1 Need some help getting this fixed and ready for merge?

**Comment by jeroz1** [comment]
Closing since scotty made an updated version

**Pull request closed without merging**
